name: flutter_google_places_sdk_web
description: The web implementation of Flutter plugin for google places sdk
version: 0.1.3
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_web

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.2.4+1
  js: ^0.6.3
  google_maps: ^6.1.0
  collection: ^1.15.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.11

flutter:
  plugin:
    platforms:
      web:
        fileName: flutter_google_places_sdk_web.dart
        pluginClass: FlutterGooglePlacesSdkWebPlugin
