name: flutter_google_places_sdk
description: Access google maps native sdk
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.8
  flutter_google_places_sdk_platform_interface:
      path: '../flutter_google_places_sdk_platform_interface'
#  flutter_google_places_sdk_platform_interface: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.msh.flutter_google_places_sdk
        pluginClass: FlutterGooglePlacesSdkPlugin
      ios:
        pluginClass: FlutterGooglePlacesSdkPlugin
