name: FlutterIntegrationTests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  flutter_version: "2.5.1"
  java_version: "16.x"
  dir: "flutter_google_places_sdk"

jobs:
  setup:
    name: Checkout and analyze
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.dir }}/example
      - name: Flutter Analyze
        run: flutter analyze
        working-directory: ${{ env.dir }}

  tests_ios:
    name: Run iOS tests on [${{ matrix.os }}] - [${{ matrix.device }}]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        device:
          - iPhone 8 (14.5)
          # - iPhone 11 Pro Max (13.1)
        os: [ macos-latest ]
        needs: setup
        include:
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter

    steps:
      - name: List all simulators
        if: ${{ matrix.os == 'macos-latest' }}
        run: xcrun instruments -s
      - name: Start Simulator
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Flutter version
        run: flutter --version
      - name: Integration Test
        run: flutter test integration_test/
        working-directory: ${{ env.dir }}/example
        env:
          PLACES_API_KEY: ${{ secrets.PLACES_API_KEY }}


  tests_android:
    name: Run android tests on [${{ matrix.os }}] - [${{ matrix.device }}]
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        api-level: [ 21, 29 ]
        target: [ default ]
        needs: setup
        include:
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Flutter version
        run: flutter --version
      - name: Integration Test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test
          working-directory: ${{ env.dir }}/example
          env:
            PLACES_API_KEY: ${{ secrets.PLACES_API_KEY }}

